# MAE 598 - Homework #2
Sebastian Garcia

In [43]:
import scipy as sp
from scipy.optimize import minimize

f = lambda x:  (1-2*x[1]-3*x[2]+1)**2+(x[1])**2+(x[2]-1)**2

cons = {'type':'eq','fun': lambda x: (x[0]+2*x[1]+3*x[2]-1)}
       
res = minimize(f,(-1,0,1),method = 'SLSQP',constraints = cons)
res



     fun: 0.07142857142857192
     jac: array([ 0.00000000e+00, -7.45058060e-09,  5.58793545e-09])
 message: 'Optimization terminated successfully'
    nfev: 21
     nit: 5
    njev: 5
  status: 0
 success: True
       x: array([-1.07142855, -0.14285714,  0.78571428])

   Problem 2B - Gradient Descent


In [78]:
import numpy as np
import scipy
from scipy.optimize import optimize

def fun(x):
    return 5 * x[0] ** 2 + 12 * x[0] * x[1] - 8 * x[1] + 10 * x[1] ** 2 - 14 * x[1] + 4

def gradiant(x):
     return np.array([10 * x[0] + 12 * x[1] - 8, 12 * x[0] + 20 * x[1] - 14])
    
eps = 1e-3
x0 = (8, -6)
k = 0
soln = [x0]
x = soln[k]
error = scipy.linalg.norm(grad(x))
a = 0.01

In [79]:
def line_search(x):
    a = 0.01
    d = -1 * gradiant(x)
    def pi(a, x):
        return fun(x) - a * 0.8 * np.matmul(np.transpose(gradiant(x)), d)
    while pi(a, x) < fun(x - a * gradiant(x)):
        a = 0.5 * a
    return a

In [74]:
while error >= eps:
    a = line_search(x)
    x = x - a * gradiant(x)
    soln.append(x)
    error = scipy.linalg.norm(gradiant(x))
    
soln


[(0, 0),
 array([0.08, 0.14]),
 array([0.1352, 0.2424]),
 array([0.172592, 0.317696]),
 array([0.19720928, 0.37344576]),
 array([0.21267486, 0.41509149]),
 array([0.2215964 , 0.44655221]),
 array([0.22585049, 0.4706502 ]),
 array([0.22678742, 0.4894181 ]),
 array([0.2253785 , 0.50431999]),
 array([0.22232225, 0.51641057]),
 array([0.21812076, 0.52644979]),
 array([0.21313471, 0.53498534]),
 array([0.207623  , 0.54241211]),
 array([0.20177124, 0.54901493]),
 array([0.19571233, 0.55499939]),
 array([0.18954117, 0.56051403]),
 array([0.18332537, 0.56566629]),
 array([0.17711288, 0.57053398]),
 array([0.17093751, 0.57517364]),
 array([0.16482292, 0.57962641]),
 array([0.15878546, 0.58392238]),
 array([0.15283623, 0.58808365]),
 array([0.14698257, 0.59212657]),
 array([0.14122912, 0.59606335]),
 array([0.13557861, 0.59990318]),
 array([0.13003237, 0.60365311]),
 array([0.12459076, 0.60731861]),
 array([0.11925345, 0.610904  ]),
 array([0.11401962, 0.61441278]),
 array([0.10888813, 0.6178478

Initial Solution: (2,2)

In [ ]:
x0 = (2, 2)

In [77]:
while error >= eps:
    a = line_search(x)
    x = x - a * gradiant(x)
    soln.append(x)
    error = scipy.linalg.norm(gradiant(x))
soln


[(2, 2),
 array([1.64, 1.5 ]),
 array([1.376 , 1.1432]),
 array([1.181216, 0.88944 ]),
 array([1.0363616 , 0.70980608]),
 array([0.92754871, 0.58348147]),
 array([0.84477606, 0.49547933]),
 array([0.78084094, 0.43501034]),
 array([0.7305556 , 0.39430736]),
 array([0.69018316, 0.36777921]),
 array([0.65703134, 0.35140139]),
 array([0.62916004, 0.34227735]),
 array([0.60517075, 0.33832268]),
 array([0.58405495, 0.33803765]),
 array([0.56508494, 0.34034353]),
 array([0.54773522, 0.34446463]),
 array([0.53162595, 0.34984348]),
 array([0.51648213, 0.35607967]),
 array([0.50210436, 0.36288588]),
 array([0.48834762, 0.37005618]),
 array([0.47510612, 0.37744323]),
 array([0.46230232, 0.38494185]),
 array([0.44987906, 0.3924772 ]),
 array([0.43779389, 0.39999627]),
 array([0.42601495, 0.40746175]),
 array([0.41451804, 0.41484761]),
 array([0.40328453, 0.42213592]),
 array([0.39229976, 0.42931459]),
 array([0.38155204, 0.4363757 ]),
 array([0.37103175, 0.44331432]),
 array([0.36073086, 0.4501276

Initial guess: (8,-6)

In [ ]:
x0 = (8, -6)

In [80]:
while error >= eps:
    a = line_search(x)
    x = x - a * gradiant(x)
    soln.append(x)
    error = scipy.linalg.norm(gradiant(x))
soln


[(8, -6),
 array([ 8.  , -5.62]),
 array([ 7.9544, -5.316 ]),
 array([ 7.87688 , -5.067328]),
 array([ 7.77727136, -4.859088  ]),
 array([ 7.66263478, -4.68054296]),
 array([ 7.53803646, -4.52395054]),
 array([ 7.40710688, -4.38372481]),
 array([ 7.27244317, -4.25583267]),
 array([ 7.13589877, -4.13735932]),
 array([ 6.99879201, -4.02619531]),
 array([ 6.86205625, -3.92081129]),
 array([ 6.72634798, -3.82009578]),
 array([ 6.59212468, -3.72323838]),
 array([ 6.45970081, -3.62964567]),
 array([ 6.32928821, -3.53888063]),
 array([ 6.20102507, -3.45061909]),
 array([ 6.07499685, -3.36461828]),
 array([ 5.95125136, -3.28069425]),
 array([ 5.82980953, -3.19870556]),
 array([ 5.71067325, -3.11854159]),
 array([ 5.59383091, -3.04011406]),
 array([ 5.47926151, -2.96335096]),
 array([ 5.36693747, -2.88819215]),
 array([ 5.25682678, -2.81458622]),
 array([ 5.14889445, -2.74248819]),
 array([ 5.04310359, -2.67185788]),
 array([ 4.93941618, -2.60265874]),
 array([ 4.83779361, -2.53485693]),
 array